config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :events do
    resources :appointments, only: [:new, :create]
  end

  root to: "pages#home"  # Defines the root path route ("/")

  resources :appointments, only: [:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  # validates :timeslot, presence: true
  # validates :timeslot, uniqueness: { scope: :event_id }
  attr_accessor :title, :start, :end, :url
  attr_accessor :start_time, :end_time
  attr_accessor :description, :location, :price
  attr_accessor :category, :specialty, :stage_name
  attr_accessor :event_date
  attr_accessor :user_id, :event_id
  attr_accessor :cpf
  attr_accessor :email
  attr_accessor :password
  attr_accessor :name
  attr_accessor :local
  attr_accessor :event_id
  attr_accessor :event_date
  attr_accessor :price
  attr_accessor :timeslot
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user! [:destroy, :create, :new] # ou outro método de autenticação
  # before_action :authorize_destroy, only: [:destroy]
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

def index
  @appointments = Appointment.all
end

def show
  @appointment = Appointment.find(params[:id])
  # @event = Event.find(params[:id])
end

def new
  @appointment = Appointment.new
  raise
 end

def create
  @event = Event.find(params[:event_id])
  @appointment = Appointment.new
  @appointment.user = current_user
  @appointment.event = @event
  if @appointment.save
    redirect_to appointment_path(@appointment)
  else
    raise
    render :new
  end
end

def edit
  @appointment = Appointment.find(params[:id])
end

def update
  @appointment = Appointment.find(params[:id])
  @appointment.update(appointment_params)
  redirect_to appointment_path(@appointment)
end

def destroy
  @appointment = Appointment.find(params[:id])
  @appointment.destroy
  redirect_to appointments_path
end

def checkout
  @appointment = Appointment.find(params[:appointment_id])
end

# def date
#   timeslot.to_date
# end

# def time
#   timeslot.strftime("%H:%M")
# end

  private

def appointment_params
  params.require(:appointment).permit(:event_id, :user_id, :timeslot)
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy, :create, :new, :edit, :update]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @appointment = Appointment.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: 'Event was successfully destroyed.'
  end


  private

  def event_params
    params.require(:event).permit(:photo, :stage_name, :category, :specialty, :description, :local, :event_date, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  # def categoria
  # end

  # def pagamento
  # end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, url: appointments_path, method: :post) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/checkout.html.erb
    <section>
      <div class="product">
        <%= image_tag "https://i.imgur.com/EHyR2nP.png", alt: "The cover of Stubborn Attachments" %>
        <div class="description">
          <h3>Stubborn Attachments</h3>
          <h5>$20.00</h5>
        </div>
      </div>
      <%= form_tag '/create-checkout-session', method: :post do %>
        <%= submit_tag 'Checkout', id: 'checkout-button' %>
      <% end %>
    </section>

app/views/appointments/edit.html.erb
<!-- FILEPATH: /home/benjamin/code/Benyoumen/SHOWCONNECT/app/views/appointments/edit.html.erb -->

<h1>Edit Appointment</h1>

<%= form_for @appointment, url: appointment_path(@appointment), method: :patch do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div>
    <%= f.label :time %>
    <%= f.time_field :time %>
  </div>

  <%= f.submit "Update Appointment" %>
<% end %>

app/views/appointments/index.html.erb
<div class="appointments-container">
  <h1>Appointments</h1>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Location</th>
        <!-- Add more table headers if needed -->
      </tr>
    </thead>
    <tbody>
      <% @appointments.each do |appointment| %>
        <tr>
          <td><%= appointment.timeslot ? appointment.timeslot.to_date : 'No date set' %></td>
          <td><%= appointment.timeslot ? appointment.timeslot.strftime("%H:%M") : 'No time set' %></td>
          <td><%= appointment.location %></td>
          <!-- Add more table cells if needed -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/appointments/new.html.erb
<!-- FILEPATH: /home/benjamin/code/Benyoumen/SHOWCONNECT/app/views/appointments/new.html.erb -->

<div class="appointment-form-container">
  <h1 class="appointment-form-title">New Appointment</h1>

  <%= form_for @appointment do |f| %>
    <div class="field">
      <%= f.label :title, class: 'form-label' %>
      <%= f.text_field :title, class: 'form-input' %>
    </div>

    <div class="field">
      <%= f.label :description, class: 'form-label' %>
      <%= f.text_area :description, class: 'form-textarea' %>
    </div>

    <div class="actions">
      <%= f.submit "Create Appointment", class: 'btn-submit' %>
    </div>
  <% end %>
</div>

app/views/appointments/show.html.erb
<!-- FILEPATH: /home/benjamin/code/Benyoumen/SHOWCONNECT/app/views/appointments/show.html.erb -->
<div class= "background-confirmação-de-evento">


<div class="appointment-details-container">
  <h1 class="appointment-details-title">Seu evento está confirmado</h1>

  <div class="appointment-info">
    <p><strong>Date:</strong> <%= @appointment.event.event_date ? @appointment.event.event_date.strftime("%d %B %Y") : 'No date set' %></p>
    <% if @appointment.event %>
      <p><strong>Event:</strong> <%= @appointment.event.stage_name %></p>

      <p><strong>Price:</strong> <%= number_to_currency(@appointment.event.price, unit: "R$ ", separator: ",", delimiter: ".") %></p>
    <% else %>
      <p>No associated event</p>
    <% end %>

<%# <div class="appointment-details-container"> %>
  <%# <h1 class="appointment-details-title">Appointment Details</h1> %>

  <%# <div class="appointment-info"> %>
    <%# <p><strong>Date:</strong> <%= @appointment.timeslot ? @appointment.timeslot.to_date : 'No date set' %>
    <%# <p><strong>Time:</strong> <%= @appointment.timeslot ? @appointment.timeslot.strftime("%H:%M") : 'No time set' %>
    <!-- Add more appointment details as needed -->
  <%# </div> %>

  <!-- You can also add links or buttons to edit or delete the appointment -->
<%# </div> %>
  </div>
</div>

app/views/appointments/success.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thanks for your order!</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>
      We appreciate your business! If you have any questions, please email
      <a href="mailto:orders@example.com">orders@example.com</a>.
    </p>
  </section>
</body>
</html>

app/views/events/_form.html.erb
<%= form_with(model: @event, url: events_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="new-event-container" >

  <h1 class="new-event-title">Edit Event</h1>

  <%= simple_form_for( @event, html: { class: 'new-event-form' } ) do |f| %>

    <%= f.input :stage_name, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :category, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :specialty, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :description, as: :text, label_html: { class: 'form-label' }, input_html: { class: 'form-textarea' } %>

    <%= f.input :local, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :event_date, as: :date, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :price, as: :string, label_html: { class: 'form-label' }, input_html: { class: 'form-input', placeholder: 'R$' } %>

    <%= f.input :photo, as: :file %>

    <%= f.button :submit, "Save Event", class: 'btn-submit' %>

  <% end %>
</div>

app/views/events/new.html.erb
<!-- FILEPATH: /home/benjamin/code/Benyoumen/SHOWCONNECT/app/views/events/new.html.erb -->

<div class="new-event-container">
  <h1 class="new-event-title">New Event</h1>

  <%= simple_form_for( @event, html: { class: 'new-event-form' } ) do |f| %>

    <%= f.input :stage_name, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :category, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :specialty, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :description, as: :text, label_html: { class: 'form-label' }, input_html: { class: 'form-textarea' } %>

    <%= f.input :local, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :event_date, as: :date, label_html: { class: 'form-label' }, input_html: { class: 'form-input' } %>

    <%= f.input :price, as: :string, label_html: { class: 'form-label' }, input_html: { class: 'form-input', placeholder: 'R$' } %>

    <%= f.input :photo, as: :file %>
    
    <%= f.button :submit, "Create Event", class: 'btn-submit' %>

  <% end %>
</div>

app/views/events/show.html.erb
<div class="margin-top-200">

<div class="event-detail-container">
  <%# <h1 class="event-detail-title">Event Details</h1> %>
  <h1 class="event-detail-title"><%= @event.stage_name %></h1>

  <div class="event-detail-card">

    <p class="event-detail"><strong>Category:</strong> <%= @event.category %></p>
    <p class="event-detail"><strong>Specialty:</strong> <%= @event.specialty %></p>
    <p class="event-detail"><strong>Description:</strong> <%= @event.description %></p>
    <p class="event-detail"><strong>Location:</strong> <%= @event.local %></p>
    <p class="event-detail"><strong>Date:</strong> <%= @event.event_date.strftime("%d %B %Y") %></p>
    <p class="event-detail"><strong>Price:</strong> <%= number_to_currency(@event.price, unit: "R$ ", separator: ",", delimiter: ".") %></p>

    <%= link_to "Edit", edit_event_path, class: "btn btn-success rounded" %>
    <%= link_to 'Delete', event_path, class: "btn btn-danger rounded", data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>

 <%# // Checar redirecionamento para o checkout %>
    <%# <%= link_to 'Contratar',appointments_path, class: 'btn-contratar', method: :post %>
  <%= simple_form_for [@event, @appointment], method: :post do |f| %>
    <%= f.submit "Contratar", class:"btn btn-primary rounded"%>
  <% end %>

  <% if @event.photo.key %>
    <%= cl_image_tag @event.photo.key, class: "card-img-top" %>
  <% else %>
    <%= image_tag "https://images.unsplash.com/photo-1604177052603-c2b4cff228db?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2hvd3xlbnwwfHwwfHx8MA%3D%3D",class: "card-img-top" %>
  <% end %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showconnect</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.4.min.js' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

  <footer>
    <i class="fa-regular fa-copyright"></i>
    <%= "Show Connect Company" %>
  </footer>

  </body>
</html>

app/views/pages/categorias.html.erb
<h1>categorias</h1>
<%= link_to "Back to home", root_path() %>
<%= link_to "payments", payments_path() %>

app/views/pages/categories.html.erb
<h1>categorias</h1>
<%= link_to "Back to home", root_path() %>
<%= link_to "payments", payments_path() %>

app/views/pages/home.html.erb
<section class="hero">
  <div class="hero-content">
      <h1>Welcome to your Party</h1>
      <p>Discover a world of attractions.</p>
      <button class="btn-primary"><%= link_to "Find your artist", events_path %></button>

  </div>

</section>

app/views/pages/pagamentos.html.erb
<h1>pagamentos</h1>
<%= link_to "back to home", root_path() %>
<%= link_to "categories", categories_path() %>

app/views/pages/payment.html.erb
<h1>pagamentos</h1>
<%= link_to "back to home", root_path() %>
<%= link_to "categories", categories_path() %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="super-div">
<div class="navbar">
  <div class="navbar-logo">
    <%= link_to root_path do %>
      <%= image_tag 'logo-ok.png', alt: 'Logo' %>
    <% end %>
  </div>
  <ul class="navbar-links">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" id="contactDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Contact
      </a>
      <div class="dropdown-menu" aria-labelledby="contactDropdown">
        <a class="dropdown-item" href="https://api.whatsapp.com/send?phone=SEUNUMERODOTELEFONE" target="_blank">
          <span class="icon"><i class="fa-brands fa-whatsapp"></i></span>
          <span class="text">Whatsapp</span>
        </a>
        <a class="dropdown-item" href="mailto:seuemail@gmail.com" target="_blank">
          <span class="icon"><i class="fa-regular fa-envelope"></i></span>
          <span class="text">Email</span>
        </a>
      </div>
    </li>
    <li>
      <% if current_user  %>
        <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete} %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </li>
  </ul>
</div>


</div>